#!/bin/bash
# Valoare implicita
DEBUG_MODE="off"  

function show_help() {
  clear
  echo "----------------------------------------------------------------------"
  echo "HELP - Backup avansat de fisiere"
  echo "----------------------------------------------------------------------"
  echo "Optiuni scurte:"
  echo "  -h, --help        Afiseaza acest mesaj de ajutor"
  echo "  -u, --usage       Afiseaza modul de utilizare"
  echo
  echo "Optiuni lungi:"
  echo "  --debug=on/off    Activeaza/dezactiveaza debug logs (implicit off)"
  echo
  echo "Exemple:"
  echo "  $0 --help"
  echo "  $0 -u"
  echo "  $0 --debug=on"
  echo "----------------------------------------------------------------------"
}

function show_usage() {
  clear
  echo "----------------------------------------------------------------------"
  echo "USAGE - Backup avansat de fisiere"
  echo "----------------------------------------------------------------------"
  echo "1) Rulare fara optiuni: $0 --- Scriptul intra in meniul interactiv."
  echo
  echo "2) Cu optiuni:"
  echo "     $0 --help"
  echo "     $0 --usage"
  echo "     $0 --debug=on"
  echo "----------------------------------------------------------------------"
}

TEMP=$(getopt -o hu -l help,usage,debug: -- "$@")
# Verificam codul de iesire al lui getopt (daca a parsat cu succes)
if [ $? -ne 0 ]; then
  echo "Eroare la parsarea argumentelor!" | tee -a out.log >&2
  exit 1
fi

eval set -- "$TEMP"

# Meniu optiuni:
while true; do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -u|--usage)
      show_usage
      exit 0
      ;;
    --debug)
      DEBUG_MODE="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Optiune necunoscuta: $1" | tee -a out.log >&2
      exit 1
      ;;
  esac
done

# daca este setat modul de debug, se afiseaza logurile
  if [ "$DEBUG_MODE" = "on" ]; then
    clear
    cat out.log
    exit 1
  fi

# Director "cos_gunoi" - aici mutam fisierele "sterse"
cos_gunoi="cos_gunoi"

# Functii care lucreaza cu LISTE de fisiere

# Functie care muta fisierele in "cosul de gunoi"
function sterge_fisiere() {
  local dir=$1  
  local cos_gunoi="cos_gunoi" 

  if [ ! -d "$cos_gunoi" ]; then
    mkdir "$cos_gunoi"
  fi

  if [ ! -d "$dir" ]; then
    echo "Eroare: Directorul '$dir' nu exista sau nu este valid." | tee -a out.log >&2
    return 1
  fi

  for fisier in "$dir"/*; do
    if [ -f "$fisier" ]; then
      mv "$fisier" "$cos_gunoi"
      echo "Fisier sters: $fisier" | tee -a out.log 
    else
      echo "Fisierul '$fisier' nu exista sau nu este fisier!" | tee -a out.log >&2
    fi
  done
}


# Functie pentru editarea continutului fisierelor
function editare_fisiere() {
  local dir=$1
  if [[ ! -d "$dir" ]]; then
    echo "Eroare: Directorul '$dir' nu exista sau nu este valid." | tee -a out.log >&2
    return 1
  fi

  read -p "Introdu mesajul pe care doresti sa-l adaugi in fisiere: " mesaj

  # Parcurgem toate fisierele din director
  for fisier in "$dir"/*; do
    if [[ -f "$fisier" ]]; then
      echo "$mesaj" >> "$fisier" 
      echo "S-a adaugat mesajul '$mesaj' in fisierul $fisier" | tee -a out.log 
    else
      echo "Elementul '$fisier' nu este un fisier" | tee -a out.log >&2
    fi
  done
}



# Functii care lucreaza cu UN SINGUR fisier

# Functie care sterge (muta in cosul de gunoi) un singur fisier
function sterge_fisier() {
  local dir=$1
  if [[ ! -d "$dir" ]]; then
    echo "Eroare: Directorul '$dir' nu exista sau nu este valid." | tee -a out.log >&2
    return 1
  fi
  if [ ! -d "$cos_gunoi" ]; then
    mkdir "$cos_gunoi"
  fi

  read -p "Introdu numele fisierului pe care vrei sa-l stergi din $dir: " fisier
  local fisier_cale="$dir/$fisier"
  if [ -f "$fisier_cale" ]; then
    mv "$fisier_cale" "$cos_gunoi"
    echo "Fisier sters: $fisier_cale" | tee -a out.log 
  else
    echo "Fisierul '$fisier_cale' nu exista sau nu este fisier!" | tee -a out.log >&2
  fi
}

# Functie care redenumeste un singur fisier
function redenumire_fisier() {
  local dir=$1
  if [[ ! -d "$dir" ]]; then
    echo "Eroare: Directorul '$dir' nu exista sau nu este valid." | tee -a out.log >&2
    return 1
  fi

  read -p "Introdu numele fisierului pe care vrei sa-l redenumesti din $dir: " fisier
  local fisier_cale="$dir/$fisier"

  if [ -f "$fisier_cale" ]; then
    echo "Cum doriti sa redenumiti fisierul?"
    echo "  1) Schimba complet numele"
    echo "  2) Schimba doar extensia"
    read -p "Alege 1 sau 2: " alegere

    case $alegere in
      1)
        read -p "Introduceti noul nume de fisier (fara extensie): " newName
        read -p "Introduceti extensia (ex: .txt, .old, .bak) [optional]: " newExt
        if [ -z "$newExt" ]; then
          mv "$fisier_cale" "$dir/$newName"
          echo "Fisierul '$fisier_cale' a fost redenumit in '$dir/$newName'" | tee -a out.log
        else
          mv "$fisier_cale" "$dir/${newName}${newExt}"
          echo "Fisierul '$fisier_cale' a fost redenumit in '$dir/${newName}${newExt}'" | tee -a out.log
        fi
        ;;
      2)
        read -p "Introduceti noua extensie (ex: .txt, .bak, .old): " newExt
        local filename_no_ext="${fisier%.*}"
        mv "$fisier_cale" "$dir/${filename_no_ext}${newExt}"
        echo "Fisierul '$fisier_cale' a fost redenumit in '$dir/${filename_no_ext}${newExt}'" | tee -a out.log
        ;;
      *)
        echo "Optiune invalida pentru redenumire." | tee -a out.log >&2
        ;;
    esac
  else
    echo "Fisierul '$fisier_cale' nu exista sau nu este fisier!" | tee -a out.log >&2
  fi
}

# Functie care editeaza un singur fisier cu un mesaj citit de la tastatura
function editare_fisier() {
  local dir=$1
  if [[ ! -d "$dir" ]]; then
    echo "Eroare: Directorul '$dir' nu exista sau nu este valid." | tee -a out.log >&2
    return 1
  fi

  read -p "Introdu numele fisierului pe care vrei sa-l editezi: " fisier
  local fisier_cale="$dir/$fisier"

  if [ -f "$fisier_cale" ]; then
    echo "Introdu textul pe care doresti sa-l adaugi in fisier:"
    read input_text
    echo "$input_text" >> "$fisier_cale"
    echo "S-a adaugat textul '$input_text' in fisierul $fisier_cale" | tee -a out.log 
  else
    echo "Fisierul '$fisier_cale' nu exista sau nu este fisier!" | tee -a out.log >&2
  fi
}


function cautare_dupa_permisiuni() {
    dir=$1
    if [[ ! -d "$dir" ]]; then
        echo "Eroare: Directorul '$dir' nu exista." | tee -a out.log >&2
        exit 1
    fi

    echo "Introduceti permisiunile dorite in cuvinte (ex: read, write, execute):"
    read -r perms
    perm_code=""
    case "$perms" in
        read) perm_code="r" ;;
        write) perm_code="w" ;;
        execute) perm_code="x" ;;
        read,write) perm_code="rw" ;;
        read,execute) perm_code="rx" ;;
        write,execute) perm_code="wx" ;;
        read,write,execute) perm_code="rwx" ;;
        *)
            echo "Eroare: Permisiuni invalide. Folositi read, write sau execute." | tee >(cat >&2) >> out.log
            exit 1
            ;;
    esac

    echo "Cautam fisierele din '$dir' cu permisiunile '$perms':" | tee -a out.log >&2
    # Gasim fisierele care au permisiunile specificate
    find "$dir" -type f -perm -u=$perm_code
}

function organizaredimensiune() {
    dir=$1  
    if [[ ! -d "$dir" ]]; then
        echo "Eroare: Directorul '$dir' nu exista." | tee -a out.log >&2
        exit 1
    fi

    echo "Organizam fisierele din directorul '$dir' dupa dimensiune:"

    # Afiseaza fisierele sortate dupa dimensiune in ordine descrescatoare
    find "$dir" -type f -exec stat --format="%s %n" {} + | sort -rh | awk '{print $2}' | tee -a out.log
}

# Gaseste fisierele cu acelasi continut
gasire_duplicate() {
    echo "Se executa functia: gasire_duplicate()" >> out.log
    local director=$1 

    #verificam daca avem argumente
    if [[ -z $director ]]; then
        echo "Nu sunt destule argumente" | tee -a out.log >&2
        return 1
    fi

    #verificam daca directorul introdus exista
    if [[ ! -d $director ]]; then
        echo "Directorul nu exista" | tee -a out.log >&2
        return 1
    fi

    #Cautam fisierele duplicate si le afisam mesaj cand se intalnesc
    #Parcurgem fisierele din director, verificand daca sunt fisiere si le comparam intre ele cu ajutorul lui cmp, cu conditia ca fisierul sa fie diferit de sine insusi
    find "$director" -type f | while read -r file1; do
        find "$director" -type f | while read -r file2; do
            if [ "$file1" != "$file2" ] && cmp -s "$file1" "$file2"; then
                echo "Fisierul $file1 are acelasi continut ca fisierul $file2" | tee -a out.log
            fi
        done
    done
    
    echo "Functia a fost executata!" >> out.log
}

# Gasire fisiere duplicate cu acelasi nume (dar cu extensii diferite)
gasire_duplicate_nume() {

    echo "Se executa functia: gasire_duplicate_nume()" >> out.log
    local director="$1"

    #verificam daca sunt destule argumnete
    if [[ -z $director ]]; then
        echo "Nu sunt destule argumente" | tee -a out.log >&2
        return 1
    fi

    #verificam daca exista directorul
    if [[ ! -d "$director" ]]; then
        echo "Directorul nu exista" | tee -a out.log >&2
        return 1
    fi

    #Cautam fisierele si extragem doar numele acestora(fara cale)
    #Renuntam la extensie si le sortam in functie de nume
    #uniq -d este folosit pentru a identifica si lista doar elementele care se repeta(numele fisierelor)
    find "$director" -type f | sed 's|.*/||' | sed 's/\.[^.]*$//' | sort | uniq -d | while read -r nume; do
        echo "Duplicatele fara extensie cu numele: '$nume':"
        find "$director" -type f -name "*$nume*" -print
        echo "-----------------------------"
    done
    
    echo "Functia a fost executata!" >> out.log
}

# Converteste data introdusa de utilizator in formatul standard yyyy-mm-dd si verifica daca o data este valida si se potriveste cu o data calendaristica acceptata
convert_data() {

  echo "Se executa functia: convert_data()" >> out.log
  local data="$1"
  
  if [[ $data =~ ^[0-9]{4}/[0-9]{2}/[0-9]{2}$ ]]; then
    echo "$data" | sed 's@/@-@g'
  elif [[ $data =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    echo "$data"
  elif [[ $data =~ ^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$ ]]; then
    echo "$data" | sed 's@\.@-@g'
  elif [[ $data =~ ^[0-9]{2}/[0-9]{2}/[0-9]{4}$ ]] || [[ $data =~ ^[0-9]{2}-[0-9]{2}-[0-9]{4}$ ]] || [[ $data =~ ^[0-9]{2}\.[0-9]{2}\.[0-9]{4}$ ]]; then
    local delim="/"
    
    # Determinam delimitatorul
    if [[ $data =~ "-" ]]; then 
      delim="-"
    elif [[ $data =~ \. ]]; then 
      delim="."
    fi

    # Extragem ziua luna anul
    ziua=$(echo "$data" | awk -F"$delim" '{print $1}' | sed 's/^0*//')
    luna=$(echo "$data" | awk -F"$delim" '{print $2}' | sed 's/^0*//')
    anul=$(echo "$data" | awk -F"$delim" '{print $3}')

    # Verificam conditii de baza
    if (( ziua == 0 || luna == 0 )); then
      echo "Ziua sau luna nu pot fi 0!" | tee -a out.log >&2
      exit 1
    elif (( ziua > 12 && luna <= 12 )); then
      ziua_noua=$ziua
      luna_noua=$luna
    elif (( ziua <= 12 && luna > 12 )); then
      ziua_noua=$luna
      luna_noua=$ziua
    elif (( ziua <= 12 && luna <= 12 )); then
      ziua_noua=$ziua
      luna_noua=$luna
    else
      echo "Nu exista asemenea data in calendar" | tee -a out.log >&2
      exit 1
    fi

    # Verificam datele calendaristice sa fie ca in calendar
    if (( ziua_noua > 31 )); then
      echo "Nu exista asemenea data in calendar" | tee -a out.log >&2
      exit 1
    elif (( ziua_noua == 31 && luna_noua != 1 && luna_noua != 3 && luna_noua != 5 && luna_noua != 7 && luna_noua != 8 && luna_noua != 10 && luna_noua != 12 )); then
      echo "Nu exista asemenea data in calendar!" | tee -a out.log >&2
      exit 1
    elif (( ziua_noua == 30 && luna_noua != 4 && luna_noua != 6 && luna_noua != 9 && luna_noua != 11 )); then
      echo "Nu exista asemenea data in calendar!" | tee -a out.log >&2
      exit 1
    elif (( ziua_noua == 29 && luna_noua == 2 && ! ((anul % 4 == 0 && (anul % 100 != 0 || anul % 400 == 0))))); then
      echo "Nu exista asemenea data in calendar!" | tee -a out.log >&2
      exit 1
    else
      printf "%04d-%02d-%02d\n" "$anul" "$luna_noua" "$ziua_noua" | tee -a out.log
    fi
  else
    echo "Format invalid. " | tee -a out.log >&2
    exit 1
  fi
  
  echo "Functia a fost executata!" >> out.log
}

# Calculam data corespunzatoare duratei de timp introduse de utilizator
calculam_data() {
  
  echo "Se executa functia: calculam_data()" >> out.log
  local input=$1
  
  # Verificam dacă input-ul este valid
  if [[ $input =~ ^[0-9]+[dwmy]$ ]]; then
    local unit=${input: -1}
    local value=${input%?}
    local offset
    
    case $unit in
      d) offset="${value} days ago" ;;
      w) offset="$(($value * 7)) days ago" ;;
      m) offset="${value} months ago" ;;
      y) offset="${value} years ago" ;;
      *) echo "Unitate de timp invalida" | tee -a out.log >&2; return 1 ;;
    esac

    # Calculam data
    local target_date=$(date -d "$offset" +%Y-%m-%d)
    echo "$target_date"
    return 0
  else
    echo "Format invalid." | tee -a out.log >&2
    return 1
  fi
  
  echo "Functia a fost executata!" >> out.log
}

# Gasim fisierele care indeplinesc conditiile
gasire_fisiere() {
  dir="$1"

  # Verificam daca directorul este valid
  if [[ ! -d "$dir" ]]; then
    echo "Director invalid: $dir" | tee -a out.log >&2
    exit 1
  fi

  echo  "Introduceti data calendaristica dorita sau durata de timp cu sufixul corespunzator(d,w,m,y) ."
  echo
  echo "In cazul ati ales o data calendaristica in  care atat ziua cat si luna sunt mai mici decat 12 sa tineti cont ca formatul default va fi de forma DD/MM/YYYY. Multumesc"

  read input

  if [[ $input =~ ^[0-9]{4}[-/.][0-9]{2}[-/.][0-9]{2}$ ]] || [[ $input =~ ^[0-9]{2}[-/.][0-9]{2}[-/.][0-9]{4}$ ]]; then
    data=$(convert_data "$input")
  elif [[ $input =~ ^[0-9]+[dwmy]$ ]]; then
    data=$(calculam_data "$input")
  else
    echo "Input invalid." | tee -a out.log >&2
    exit 1
  fi

  echo "Se cauta fisiere mai vechi de $data"

  # Folosim find pentru a căuta fișierele mai vechi de data specificata
  # cu ajutorul lui -not -newermt aflam daca fisierul nu este mai nou modificat decat data introdusa
  find "$dir" -type f -not -newermt "$data"
}

#Functie pentru mutarea fisierelor local dintr un director sursa in directorul destinatie
#Functie care preia ca argument numele directorului in care se gasesc fisierele dorite si numele destinatiei in care vrea utilizatorul sa mute fisierele 
# folosim xargs si mutam toate fisierele care au fost gasite folosind mv in destinatie
mutare_fisier_local() {
    echo "Se executa functia: mutare_fisier_local()" >> out.log
    sursa="$1"
    destinatie="$2"
    
    # Verificam dacă sursa exista si este un director
    if [ ! -d "$sursa" ]; then
        echo "Locatia sursa $sursa nu exista pe acest dispozitiv." | tee -a out.log >&2
        return 1
    fi

    # Verificam daca destinatia exista, daca nu, o cream
    if [ ! -d "$destinatie" ]; then
        echo "Locatia destinatie $destinatie nu exista pe acest dispozitiv." | tee -a out.log
        if mkdir -p "$destinatie"; then
            echo "Locatia destinatie $destinatie a fost creata cu succes." | tee -a out.log
        else
            echo "Eroare la crearea directorului $destinatie" | tee -a out.log >&2
            return 1
        fi
    else
        echo "Locatia destinatie $destinatie exista deja pe acest dispozitiv." | tee -a out.log
    fi

    # folosim realpath pentru a extrage calea absoluta atat [entru sursa cat si pentru destinatie 
    # verificam daca cele doua sunt acelasi lucru pentru a evita eroarea cauzata de suprascrierea fisierelor 
    cale_absoluta_sursa=$(realpath "$sursa")
    cale_absoluta_destinatie=$(realpath "$destinatie")
    
    if [ "$cale_absoluta_sursa" = "$cale_absoluta_destinatie" ]; then 
    	echo "Eroare: sursa si destinatia sunt identice. Introduceti o destinatie diferita de sursa "  | tee -a out.log >&2
    	return 1
    fi 
    # extragem in nume_script numele scriptului 
    # folosim $0 pentru a extrage calea curenta spre script , iar folosind basename extragem doar numele propriu zis
    # folosim grep -v pentru a exclude din fisiere scriptul curent
    nume_script="$(basename "$0")"
    find "$sursa" -type f -print0 | grep -z -v "$nume_script" | xargs -0 -I {} mv {} "$destinatie" \
        && echo "Fisierele au fost mutate cu succes in $destinatie." | tee -a out.log \
        || echo "Eroare la mutarea fisierelor în $destinatie." | tee -a out.log >&2
}


#Functie care asigura atat configurarea git ului cat si a Github ului 
configurare_git(){
    #realizeaza configurarea locala a user ului si a email ului 
    echo "Introduceți username-ul pentru Git:"
    read -r user
    
    echo "Introduceți email-ul pentru Git:"
    read -r email
    
     if git config --global user.name "$user" && git config --global user.email "$email"; then
        echo "Configurarea globala a utilizatorului și a email-ului pentru Git a fost realizată cu succes." | tee -a out.log
    else
        echo "Eroare la configurarea globala a utilizatorului sau email-ului." | tee -a out.log >&2
        return 1
    fi
    
    # Verificam daca directorul curent este un repository Git valid
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        echo "Repository-ul git este deja inițializat." | tee -a out.log 
    else
        git init && echo "Repository-ul git a fost initializat cu succes." | tee -a out.log  || echo "Eroare la initializarea repository-ului." | tee -a out.log >&2
    fi
      # Verificare și configurare remote pentru GitHub
    if git remote get-url origin >/dev/null 2>&1; then
        echo "Remote-ul pentru GitHub e configurat: $(git remote get-url origin)" | tee -a out.log 
    else
        echo "Remote-ul pentru GitHub nu este inca configurat." | tee -a out.log 
        echo "Introduceti URL-ul repository-ului dumneavoastra de GitHub : " 
        read link_GitHub
        git remote add origin "$link_GitHub" && echo "Remote-ul GitHub a fost configurat cu succes." ||  echo "Au fost intampinate probleme la configurarea remote-ului GitHub."
    fi
    
    # Verificare autentificare GitHub
    branch=$(git branch --show-current)
    if [ -z "$branch" ]; then
        echo "Nu exista un branch curent." | tee -a out.log
        git checkout -b main && echo "Branch ul main a fost creat cu succes " | tee -a out.log ||  echo "Branch-ului 'main' nu a putut fi creat." | tee -a out.log >&2
        branch="main"
    fi
    # se simuleaza un push pentru git fara a l realiza 
    # daca simularea esueaza inseamna ca este necesara autentificarea
    if ! git push --dry-run origin "$branch" >/dev/null 2>&1; then
        echo "Este necesar sa va autentificati pe GitHub. Configurati un token personal pe platforma de Github" | tee -a out.log 
        return 1
    fi
    echo "Repository-ul este configurat corect pentru GitHub." | tee -a out.log 
}


#Functie care adauga fisierul specificat de utilizator in git , dar si sincronizarea intr o locatie externa (GitHub)
adaugare_fisier_in_git(){
   configurare_git
   fisier=$1
   if [ ! -f "$fisier" ]; then
       echo "Fisierul $fisier nu exista."  | tee -a out.log >&2
       touch "$fisier" && echo "Fisierul $fisier a fost creat cu succes" | tee -a out.log || echo "Eroare la crearea fișierului $fisier" | tee -a out.log >&2
   fi
   #verificam daca fisierul se gaseste deja in Git 
   if git ls-files --error-unmatch "$fisier" >/dev/null 2>&1; then
       if git diff --quiet "$fisier"; then
           echo "Fisierul $fisier exista deja in Git. Acesta nu a fost actualizat, astfel nu necesita readaugare in Git" | tee -a out.log
       else
           echo "Fișierul $fisier exista deja in Git, dar a fost modificat local. Actualizam $fisier în Git" | tee -a out.log
           git add "$fisier" && echo "Fisierul a fost adaugat cu succes in staging area " | tee -a out.log || echo "Au fost intampinate probleme la adaugarea in staging area " | tee -a out.log >&2
           git commit -m "Actualizare fisier $fisier" | tee -a out.log  || echo "Commit ul nu poate fi realizat." | tee -a out.log >&2
       fi
   else
       git add "$fisier"
       git commit -m "Am adaugat fisierul $fisier in Git" | tee -a out.log  || echo "Commit ul nu poate fi realizat." | tee -a out.log >&2
   fi
   ## obtinem branch ul curent
   branch_curent=$(git branch --show-current)
   if [ -z "$branch_curent" ]; then
       echo "Nu exista un branch curent activ." | tee -a out.log 
       ## cream un branch numit main si ne mutam pe acesta folosind comanda git checkout -b 
       ## puteam folosi pentru a crea branch si comanda git branch insa nu ne si muta pe aceasta
       git checkout -b main && echo "Branch ul main a fost creat cu succes" | tee -a out.log ||  echo "Branch-ului 'main' nu a putut fi creat " | tee -a out.log >&2
       branch_curent="main"
   fi
   git push -u origin "$branch_curent" && echo "Fisierul $fisier a fost adăugat cu succes în Git si sincronizat cu GitHub." | tee -a out.log ||  echo "Eroare la sincronizarea cu GitHub." | tee -a out.log >&2
}


# Restaureaza fisierele care se afla in cosul de gunoi
restaurare_fisiere() {

  echo "Se executa functia restaurare_fisiere()" >> out.log
  # Directorul cos_gunoi
  cos_gunoi="cos_gunoi"

  # Directorul unde vor fi mutate fisierele restaurate
  fisiere_restaurate="fisiere_restaurate"

  # Verificam daca exista directorul cos de gunoi
  if [ ! -d "$cos_gunoi" ]; then
    echo "Directorul '$cos_gunoi' nu exista!" | tee -a out.log >&2
    exit 1
  fi

  # Cream directorul fisiere_restaurate daca nu exista
  mkdir -p "$fisiere_restaurate"

  # Cerem utilizatorului sa specifice fisierul sau tipul de fisiere
  echo "Introduceti numele fisierului sau un sablon (ex: *.txt):"
  read -r input

  # Verificam daca exista fisiere care corespund sablonului
  fisiere_de_mutat=$(find "$cos_gunoi" -type f -name "$input")

  # Verificam daca exista fisiere gasite
  if [ -z "$fisiere_de_mutat" ]; then
    echo "Nu au fost gasite fisiere care sa corespunda sablonului '$input'." | tee -a out.log >&2
    exit 0
  fi

  # Mutam fisierele care corespund sablonului
  for fisier in $fisiere_de_mutat; do
    # Preluam numele fisierului, fara calea completa
    nume_fisier=$(basename "$fisier")
    
    # Efectuam mutarea
    mv "$fisier" "$fisiere_restaurate/$nume_fisier"
    echo "Fisier mutat: $nume_fisier -> $fisiere_restaurate" | tee -a out.log
  done
  
  echo "S-a incheiat executia!" >> out.log
}



# functie pentru stergerea fisierelor mai vechi de 60 de zile  -- NU VA FI APELATA IN MENIU
sterge_fisiere_vechi() {

    echo "Se executa functia sterge_fisiere_vechi()" >> out.log
    director="$1"

    if [ ! -d "$director" ]; then
        echo "Eroare: Directorul '$director' nu exista." | tee -a out.log >&2
        return
    fi
    # cauta fisierele mai vechi de 60 de zile si le sterge
    find "$director" -type f -mtime +60 -exec rm -f {} \;
    echo "Fisierele mai vechi de 60 de zile au fost sterse din '$director'." | tee -a out.log 
    echo "Functia a fost executata!" >> out.log
}

# functie pentru programarea stergerii in fiecare luni la ora 20:00   -- va fi apelata in meniu: stergere_programata <nume_director>
stergere_programata() {
	
    echo "Se executa functia stergere_programata()" >> out.log
    director="$1"

    if [ ! -d "$director" ]; then
        echo "Eroare: Directorul '$director' nu exista." | tee -a out.log >&2
        return
    fi
    # salvam calea scriptului
    script_path="$PWD/$(basename "$0")"
    # specificam ce va fi scris in crontab (se va executa scriptul lunea la ora 20:00)
    cron_entry="0 20 * * 1 $script_path sterge_fisiere_vechi \"$director\""

    # Verifica daca cronjob-ul exista deja
    if ! crontab -l 2>/dev/null | grep -F "$cron_entry" >/dev/null; then
        (crontab -l 2>/dev/null; echo "$cron_entry") | crontab -
        echo "Cronjob adaugat: Sterge fisierele mai vechi de 60 de zile in fiecare luni la ora 20:00 din '$director'." | tee -a out.log
    else
        echo "Cronjob-ul exista deja." | tee -a out.log >&2
    fi
    echo "Functia a fost executata!" >> out.log
}

# Meniu interactiv
echo "Introdu numele directorului:"
read dir
while true; do
  sleep 3
  clear
  echo "Meniu:"
  echo "1) Stergere toate fisierele din director"
  echo "2) Editare toate fisierele din director"
  echo "3) Sterge un fisier"
  echo "4) Redenumeste un fisier"
  echo "5) Editeaza un fisier"
  echo "6) Cauta fisierele in functie de permisiuni"
  echo "7) Ordoneaza fisierele dupa dimensiune"
  echo "8) Gaseste fisierele duplicate dupa continut"
  echo "9) Gaseste fisierele duplicate dupa nume"
  echo "10) Gaseste fisierele mai vechi decat o anumita data"
  echo "11) Restaureaza fisierele din cosul de gunoi"
  echo "12) Pornire stergere periodica a fisierelor din cosul de gunoi"
  echo "13) Mutarea fisierelor local intr un director specificat"
  echo "14) Mutarea fisierelor in cloud "
  echo "15) Iesire"

  # Cere alegerea utilizatorului
  read -p "Alege o optiune: " alegere

  # Executa optiunea corespunzatoare
  case $alegere in
    1)
      echo "Stergere toate fisierele din director"
      sterge_fisiere $dir
      ;;
    2)
      echo "Editare toate fisierele din director"
      editare_fisiere $dir
      ;;
    3)
      echo "Sterge un fisier"
      sterge_fisier $dir
      ;;
    4)
      echo "Redenumeste un fisier"
      redenumire_fisier $dir
      ;;
    5)
      echo "Editeaza un fisier"
      editare_fisier $dir
      ;;
    6)
	echo "Cauta fisiere dupa permisiuni"
	cautare_dupa_permisiuni $dir
	;;
    7)
   	 echo "Ordoneaza fiserele dupa dimensiune"
   	 organizaredimensiune $dir
   	 ;;
    8)
	 echo "Gaseste fisierele duplicate dupa continut"
	 gasire_duplicate $dir
	 ;;
    9)
	 echo "Gaseste fisierele duplicate dupa nume"
	 gasire_duplicate_nume $dir
	 ;;
    10)
 	 echo "Gaseste fisierele mai vechi decat o anumita data"
	 gasire_fisiere $dir
	 ;;
    11)
	 echo "Restaureaza fisierele din cosul de gunoi"
	 restaurare_fisiere $cos_gunoi
	 ;;
    12)
	 echo "Porneste stergerea periodica din cosul de gunoi"
	 stergere_programata $cos_gunoi
    	 ;;
    13) 
	echo "Introduceti directorul destinatie in care doriti sa fie mutate fisierele din $dir"
	read destinatie 
	mutare_fisier_local $dir $destinatie
	;;
    14) echo "Introduceti calea absoluta a fisierului pe care doriti sa l adaugati in cloud cu ajutorul git si GitHub"
	read fisier
	adaugare_fisier_in_git $fisier
	;;
    15) 
      echo "Iesire din script."
      ## adaugam fisierul out.log in cloud 
      adaugare_fisier_in_git out.log
      exit 0
      ;;
    *)
      echo "Optiune invalida. Incearca din nou."
      ;;
  esac
done
